### ISSUE TITLE
Simply does nothing

### ISSUE THREAD

**Issue by beceha** [inpsyde/MultilingualPress-Yoast-SEO-Sync#1]
Hi,

this plugin simply does nothing, obviously it is outdated?
No YOAST settings are copied from one post/page to those of the linked language.

YOAST 7.1 free
WP 4.9.4 multisite
PHP 7.0.25
MultilingualPress 2.11.0

**Comment by bueltge** [comment]
Hi @studioart 
Long time ago, I know. However we have a small change, maybe you will test again.
Best and thanks!
