### ISSUE TITLE
Update for MLP 3.x and WP 5.x

### ISSUE THREAD

**Issue by vheinrich** [inpsyde/MultilingualPress-Yoast-SEO-Sync#3]
We need exactly this plugin for Multilingual Press 3.x with WP 5.x. 
Support told us, the development for this plugin already started. 

Is there any scheduled release date?

**Comment by Dinamiko** [comment]
Hello @vheinrich,

Just to let you know that we are currently working on the MLP3 version of it, once finished we´ll let you know here.

Thanks,
Emili

**Comment by bueltge** [comment]
Hi @vheinrich
Now the version is inside the master and ready for a review from your side.

**Comment by bueltge** [comment]
For now it is released, the master is now for our current stable version MultilingualPress 3. So I close this issue.
