### ISSUE TITLE
No Yoast SEO tab on (custom) taxonomies

### ISSUE THREAD

**Issue by ckanitz** [inpsyde/MultilingualPress-Yoast-SEO-Sync#4]
WP: 5.2.1
MLP: 3.2.0
MLPYSS: 2.0.0

The "Yoast SEO" sync-tab does not appear on (custom) taxonomies. All tested taxonomies were checked as translatable.

**Comment by ckanitz** [comment]
Hey @Dinamiko, just pinging to ask if there is an update to that issue? :)

**Comment by Dinamiko** [comment]
Hi @ckanitz, sorry for delay :) here is current status:

Currently there is a problem with Yoast and MLP that copies Yoast SEO data (seo title, slug...) values to all connected sites, so let say that you have two sites connected in MLP and a connected taxonomy term, then you save Yoast seo title value in site 1, the current behavior is that this value is also copied to the other site, which is not correct, that value should only be stored in the current site. 

We are currently working on fixing the above problem but I´ll try to push this one during this week too, let see if we can have it done at the end of this week.

**Comment by Dinamiko** [comment]
Issue addressed in [2.1.0](https://github.com/inpsyde/MultilingualPress-Yoast-SEO-Sync/releases/tag/v2.1.0)
