### ISSUE TITLE
Fatal error: Uncaught DomainException: Empty Term.

### ISSUE THREAD

**Issue by Dinamiko** [inpsyde/MultilingualPress-Yoast-SEO-Sync#9]
**Steps to reproduce**
1. Install latest versions of MLP Yoast (2.1.1) and MLP (3.3.0)
2. Connect one site
3. Create a new post category term

**What should happen**
I should see the Yoast tab correctly in translation metabox.

**What happened instead**
A fatal error is displayed: 
```Fatal error: Uncaught DomainException: Empty Term. in .../wp-content/plugins/MultilingualPress-Yoast-SEO-Sync/src/TranslationUi/Term/Repository.php on line 41```

**Comment by mklasen** [comment]
Aside from the Yoast tab not displaying, this also breaks the full edit term page.

- The save button disappears, making it unable to edit a term
- The WYSIWYG editor for the description field is not visible anymore (this is added by the Yoast plugin)

**Comment by Kdamen1** [comment]
MLP 3.3.0 does not fix the earlier mentioned issues. Like Marinus also mentioned:
- Save button disappears
- Yoast SEO plugin does not work properly
- Description is being displayed as a plain text instead of a rich one
- Wholesale roles appear where they should not (wasn't visible in an the earlier version)

Please have this fixed ASAP since this is killing for SEO ratings.

**Comment by YourMark** [comment]
I have also encountered this.

**Comment by Dinamiko** [comment]
@mklasen, @Kdamen1, @YourMark we have just released new version 2.1.2 (https://github.com/inpsyde/MultilingualPress-Yoast-SEO-Sync/releases/tag/v2.1.2) which should fix the issue, when you have time please give it a try to see if it works for you now, otherwise let us know, thanks.

**Comment by mklasen** [comment]
Hi @Dinamiko, Thanks for your prompt reply and action. The issue seems resolved. @Kdamen1 - Can you confirm this?

**Comment by Kdamen1** [comment]
@mklasen looks good now!
